services:
  site:
    image: adamanlino/site-navix:latest
    ports:
      - "8080:8080"
    networks:
      - rede-compose
    depends_on:
      - db

  db:
    image: adamanlino/db-navix:latest
    ports:
    - "3307:3306"
    networks:
    - rede-compose
    
networks:    
  rede-compose:
    driver: bridge